<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-03T14:38:05 ICT" name="Default suite" finished-at="2025-03-03T14:38:23 ICT" duration-ms="18915">
    <groups>
    </groups>
    <test started-at="2025-03-03T14:38:05 ICT" name="Default test" finished-at="2025-03-03T14:38:23 ICT" duration-ms="18915">
      <class name="Selenium.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:Selenium.LoginTest@574b560f]" started-at="2025-03-03T14:38:05 ICT" name="setup" finished-at="2025-03-03T14:38:07 ICT" duration-ms="2474" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testLogin(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Selenium.LoginTest@574b560f]" started-at="2025-03-03T14:38:07 ICT" name="testLogin" data-provider="loginData" finished-at="2025-03-03T14:38:19 ICT" duration-ms="12396" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[hoangloi0802@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Đăng nhập thành công!]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Selenium.LoginTest@574b560f]" started-at="2025-03-03T14:38:19 ICT" name="testLogin" data-provider="loginData" finished-at="2025-03-03T14:38:21 ICT" duration-ms="1250" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[demo4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Tài khoản không tồn tại.]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Selenium.LoginTest@574b560f]" started-at="2025-03-03T14:38:21 ICT" name="testLogin" data-provider="loginData" finished-at="2025-03-03T14:38:22 ICT" duration-ms="1262" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[hoangloi0802]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[12345]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sai tài khoản hoặc mật khẩu]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Selenium.LoginTest@574b560f]" started-at="2025-03-03T14:38:22 ICT" name="testLogin" data-provider="loginData" finished-at="2025-03-03T14:38:23 ICT" duration-ms="1256" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[sai]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[345]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sai tài khoản hoặc mật khẩu]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Thông báo không đúng! expected [Sai tài khoản hoặc mật khẩu] but found [Tài khoản không tồn tại.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Thông báo không đúng! expected [Sai tài khoản hoặc mật khẩu] but found [Tài khoản không tồn tại.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at Selenium.LoginTest.testLogin(LoginTest.java:57)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Selenium.LoginTest@574b560f]" started-at="2025-03-03T14:38:23 ICT" name="teardown" finished-at="2025-03-03T14:38:23 ICT" duration-ms="214" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Selenium.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
